// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Gestion.Domain.Models;
using Microsoft.EntityFrameworkCore;

namespace Gestion.Infrastructure.Context;

public partial class GestionDbContext : DbContext
{
    public GestionDbContext(DbContextOptions<GestionDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Reserva> Reserva { get; set; }

    public virtual DbSet<Salon> Salon { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Reserva>(entity =>
        {
            entity.HasKey(e => e.IdReserva);

            entity.Property(e => e.FechaReserva).IsRequired();
            entity.Property(e => e.HoraFin).IsRequired();
            entity.Property(e => e.HoraInicio).IsRequired();
            entity.Property(e => e.NombreCliente).IsRequired();

            entity.HasOne(d => d.IdSalonNavigation).WithMany(p => p.Reserva)
                .HasForeignKey(d => d.IdSalon)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Salon>(entity =>
        {
            entity.HasKey(e => e.IdSalon);

            entity.Property(e => e.Nombre).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}