// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Domain.Models;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int IdSalon { get; set; }

    public DateTime FechaReserva { get; set; }

    public TimeSpan HoraInicio { get; set; }

    public TimeSpan HoraFin { get; set; }

    public string NombreCliente { get; set; }

    public virtual Salon IdSalonNavigation { get; set; } 
}