// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestion.Domain.Models;

public partial class Salon
{
    public int IdSalon { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Reserva> Reserva { get; set; } = new List<Reserva>();
}